repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest tests
        entry: pytest tests
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
